GET https://aravind-guvi-backend.onrender.com/all

####

POST https://aravind-guvi-backend.onrender.com/register
Content-Type: application/json

{
    "email":"mkbh@gmail.com",
    "password":"mkbh@123",
    "confirm_password":"mkbh@123"
}

###

POST https://aravind-guvi-backend.onrender.com/login
Content-Type: application/json

{
    "email":"mkbh@gmail.com",
    "password":"mkbh@123"
}

####

PUT https://aravind-guvi-backend.onrender.com/user-details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFyYXZpbmRAZ21haWwuY29tIiwiaWF0IjoxNjk4NTQyODQ2fQ.6nBa_xEzrEKsN-imZ8h_tmw4KLVPbMVaNl5QCa5010I
Content-Type: application/json

{
    
    "username":"ARA",
    "name":"Al",
    "gender":"male",
    "location":"AP",
    "email":"mkbh@gmail.com",
    "age":23,
    "mobile_num":888888444,
    "dob":"2000-08-04",
    "full_address":"kuppam,PES"
}
